#!/usr/bin/env python3
"""Build the Hermes .env file with ALL credentials in one shot."""
import os

root = "/opt/data/hermes-os"

# Load from environment or use placeholders
telegram = os.environ.get("TELEGRAM_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN")
openrouter = os.environ.get("OPENROUTER_KEY", "YOUR_OPENROUTER_API_KEY")
gemini = os.environ.get("GEMINI_API_KEY", "YOUR_GEMINI_API_KEY")
smtp_pass = os.environ.get("SMTP_PASS", "YOUR_SMTP_PASSWORD")

env = f"""# GreenTouch.Pro — Full Environment Configuration
# Generated by build script

# ─── Telegram Bot ────────────────────────────────────────────
TELEGRAM_TOKEN={telegram}
OPENROUTER_KEY={openrouter}

# ─── Google Gemini AI (for commitment detection) ────────────
GEMINI_API_KEY={gemini}
GEMINI_PROJECT_ID=greentouchpro
GEMINI_PROJECT_NUMBER=415883067268

# ─── Database ─────────────────────────────────────────────────
DB_PATH=./data/hermes.db

# ─── Email (Hostinger SMTP) ───────────────────────────────────
SMTP_HOST=smtp.hostinger.com
SMTP_PORT=465
SMTP_USER=ryan@greentouch.pro
SMTP_PASS={smtp_pass}
SMTP_FROM=ryan@greentouch.pro

# ─── Leadership (CC on critical/escalated) ───────────────────
LEADERSHIP_EMAILS=pat@greentouchbuilders.com,paul.lee@greentouchbuilders.com,graham@greentouchbuilders.com

# ─── GreenTouch Partners ──────────────────────────────────────
PARTNER_PAT=pat@greentouchbuilders.com
PARTNER_PAUL=paul.lee@greentouchbuilders.com
PARTNER_GRAHAM=graham@greentouchbuilders.com
"""

with open(os.path.join(root, ".env"), "w") as f:
    f.write(env)

# Verify
with open(os.path.join(root, ".env"), "r") as f:
    content = f.read()
    for key in ["TELEGRAM_TOKEN", "OPENROUTER_KEY", "GEMINI_API_KEY", "SMTP"]:
        if key in content:
            print(f"✅ {key} present")
        else:
            print(f"❌ {key} MISSING")